### ISSUE TITLE
No module named 'openquake.baselib.slots'

### ISSUE THREAD

**Issue by Thomas-Ulrich** [GEMScienceTools/gmpe-smtk#130]
Hi,
I've been installing openquake today with:
```
pip install -r https://raw.githubusercontent.com/gem/oq-engine/master/requirements-py38-linux64.txt openquake.engine
pip install openquake.engine
```
(oq --version 3.13.0)
Now I've clone the latest gmpe-smtk
```
git clone https://github.com/GEMScienceTools/gmpe-smtk --depth 1
```
(commit 7948682b32ef804a52d266dfcc94512da01149ab)

And I try to run some old script from me, and got:
```
(base) ulrich@ulrich-ThinkPad-T490s:~/TuSeisSolScripts/computeResponseSpectrum$ python 
Python 3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import smtk.trellis.trellis_plots as trpl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ulrich/myLibs/gmpe-smtk/smtk/trellis/trellis_plots.py", line 41, in <module>
    from smtk.trellis.configure import GSIMRupture, DEFAULT_POINT
  File "/home/ulrich/myLibs/gmpe-smtk/smtk/trellis/configure.py", line 31, in <module>
    from openquake.baselib.slots import with_slots
ModuleNotFoundError: No module named 'openquake.baselib.slots'
>>> 
```
It might be that trpl should be updated.
Best,
Thomas.

**Comment by Thomas-Ulrich** [comment]
nevermind, there was an old gmpe-folder which was in my PYTHONPATH....
